[tools]
python = "3.12"

[env]
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist
PYTHONPATH = "."
_.file = ".env.yaml"

[hooks]
enter = "echo 'Welcome to the template project'"

[tasks.test]
run = 'uv run pytest'

[tasks.cov]
run = [
  'uv run pytest --cov=src --cov-report=xml',
  'uv run coverage-badge -o docs/coverage.svg -f',
  'uv run interrogate --generate-badge docs/interrogate.svg',
]

[tasks.sec]
run = ['uv run bandit -r src']

[tasks.cov-html]
run = 'uv run pytest --cov=src --cov-report=html'

[tasks.pyright]
run = 'uv run pyright'


[tasks.be]
run = 'cd backend; pocketbase serve'

[tasks.serve]
run = 'uv run python src/app.py'
